# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    tags:
      - 'v*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
  
jobs:
  run-sript:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v6
        
      - name: Get the current tag
        if: steps.branch-name.outputs.is_tag == 'true'  # Replaces: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "Echo current tag: ${{ steps.branch-name.outputs.tag }}"
        # Outputs: "v0.0.1" OR "0.0.1"   
        
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: v1.0.0

      - uses: jungwinter/split@v2
        id: splittag
        with:
          msg: '${{ steps.branch-name.outputs.tag }}'
          separator: "-"
      - uses: web3j/substr-action@v1.2
        id: clean
        with:
          value: '${{ steps.splittag.outputs._1 }}'
          start: '0'
          length: '2'
      - name: 'Sufix'
        if: contains(fromJson('["AD", "RT", "CC", "RC"]'), steps.clean.outputs.result)
        run: echo Sufixing ${{ steps.splittag.outputs._1 }} corte ${{ steps.clean.outputs.result }}
        
      - name: 'Check tag'
        id: checktag
        run: git push --delete origin ${{ steps.branch-name.outputs.tag }}



      - uses: actions/github-script@v6
        with:
          script: |
            console.log(context)
