# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    tags:
      - 'v*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
  
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v6
        
      - name: Get the current tag
        if: steps.branch-name.outputs.is_tag == 'true'  # Replaces: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "Echo current tag: ${{ steps.branch-name.outputs.tag }}"
        # Outputs: "v0.0.1" OR "0.0.1"   
        
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
      - name: 'List tags'
        id: listags
        run: |
          echo "list = git for-each-ref --sort=taggerdate --format '%(tag)'" >> $GITHUB_OUTPUT
          echo echo ${{needs.listags.outputs.list}}
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: v1.0.0
      - uses: jungwinter/split@v2
        id: splitprevtag
        with:
          msg: '${{ steps.previoustag.outputs.tag }}'
          separator: "-"
      - uses: web3j/substr-action@v1.2
        id: cleanprev
        with:
          value: '${{ steps.splitprevtag.outputs._1 }}'
          start: '0'
          length: '2'             
      - uses: jungwinter/split@v2
        id: splittag
        with:
          msg: '${{ steps.branch-name.outputs.tag }}'
          separator: "-"
      - uses: web3j/substr-action@v1.2
        id: clean
        with:
          value: '${{ steps.splittag.outputs._1 }}'
          start: '0'
          length: '2'
      - name: 'Sufix'
        if: |
          !contains(fromJson('["AD", "RT", "CC", "RC", ""]'), steps.clean.outputs.result)
        run: |
           echo "tag prev no correcto -> ${{ steps.branch-name.outputs.tag }}"
           git push --delete origin ${{ steps.branch-name.outputs.tag }}        
          #echo "::stop-commands::$stopMarker"  
      - name: 'Create Release branch'
        if: steps.clean.outputs.result == 'CC'
        run: |
          git checkout -b release/${{ steps.splittag.outputs._0 }} ${{ steps.branch-name.outputs.tag }}
          git push origin release/${{ steps.splittag.outputs._0 }}
      - name: 'Check Tag Suffix'
        if: steps.clean.outputs.result == 'AD' && steps.cleanprev.outputs.result != ''
        run: |
           echo "tag prev no correcto -> ${{ steps.branch-name.outputs.tag }}"
           git push --delete origin ${{ steps.branch-name.outputs.tag }} 
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(context)
