name: Readme Template
on:
  schedule:
    - cron: '*/30 * * * *' # every 2 hours
  push:
    branches: [ master ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Generate README.md
      uses: probablykasper/readme-template-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        template: TEMPLATE.md
        output: README.md
    - name: Update README.md
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
          git config user.name "Barcelo"
          git config user.email "salvador.merlos@inetum.com"
          git add .
          git commit -m "Auto-update README.md"
          git push
        fi
